# =====================================================
# ==================== MY PROGRAMS ====================
# =====================================================
# Set programs that you use
$terminal = kitty
$fileManager = nautilus 
$browser = librewolf

# menus
$menu = pkill rofi || bash ~/.config/rofi/launcher.sh
$configs_menu = pkill rofi || bash ~/dotfiles/scripts/change-config.sh
$shutdown_menu = pkill rofi || bash ~/dotfiles/scripts/shutdown-menu.sh

$restart_waybar = pkill waybar; waybar &
$reload_swaync = swaync-client -R && swaync-client -rs