# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

# al tener una window, no hay gaps, pero con varias si hay
workspace = w[1], gapsout:0, gapsin:0

# para que sean borderless, cambiar bordersize a 0 o floating a 0, sino dejar 
# bordersize 2 y/o floating:0

# -------------------------
# NO ANDA DESDE OMARCHY 3.3
# -------------------------

# windowrule = bordersize 2, floating:0, onworkspace:w[1]

# para que tengan esquinas rectas, cambiar rounding a 0, sino dejar en 8

# windowrule = rounding 10, floating:0, onworkspace:w[1]