wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/walls/glass-beach-inspired.png
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/Pictures/walls/metropolis.png
    fit_mode = cover
}
